name: Send Email on Push

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Use SMTP of your email provider
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Push to Repo: ${{ github.repository }}"
          body: "A new push has been made to the repository.\n\nCommit Message: ${{ github.event.head_commit.message }}\n\nView Changes: ${{ github.event.head_commit.url }}"
          to: "rishavkapil2003@gmail.com"  # Replace with the recipient's email
          from: "GitHub Actions <rishavkapil61@gmail.com>"

